baseurl = "http://kallepalliraviteja.github.io"
languageCode = "en"
title = "KALLEPALLI RAVI TEJA"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

[params]
title = "KALLEPALLI RAVI TEJA"
description = ""
# gravatar = "kallepalliraviteja@gmail.com"
images = ["images/profile.jpg"]
profilePicture = "images/profile.jpg"
copyright = "KALLEPALLI RAVI TEJA"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"

  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/kraviteja87/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/kallepalliraviteja"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/raviteja_in"

[taxonomies]
  series = "series"
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 10
  url = "/about/"


[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
